spring:
  application:
    name: legacy-sync-cloud

  # NOVA CONFIGURAÇÃO: Onde encontrar as páginas JSP
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  # Conexão com o BD (banco de dados) PostgreSQL no Docker
  datasource:
    url: jdbc:postgresql://localhost:5432/tqi_challenge_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  # Configuração do Flyway (Controle de versão do BD (banco de dados))
  flyway:
    enabled: true
    baseline-on-migrate: true

  # Configurações do Hibernate/JPA (Java Persistence API) (Interface de Persistência Java)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  # Apontando a AWS (Amazon Web Services) (Serviços Web da Amazon) para o LocalStack
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      endpoint: http://localhost:4566

# Nossas propriedades customizadas para o FTP (File Transfer Protocol) (Protocolo de Transferência de Arquivos)
legacy:
  ftp:
    server: localhost
    port: 21
    username: admin
    password: admin
    directory: /